<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<section class="block-subscribe"> 
	<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
		<div class="title-box">
			<i class="icon-envelope-alt"></i>
			<div class="left">
				<h3><?php echo $this->__('Newsletter') ?></h3>
				<label for="newsletter"><?php echo $this->__('Subscribe to be the first to know about Sales, Events, and Exclusive Offers!') ?></label>
			</div>
			<div class="clear"></div>
		</div>
        <div class="block-content">
            <div class="input-box">
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
                <input type="text" value="<?php echo $this->__('Sign up for our newsletter') ?>" onblur="if (this.value=='') this.value = '<?php echo $this->__('Sign up for our newsletter') ?>'" onfocus="if (this.value=='<?php echo $this->__('Sign up for our newsletter') ?>') this.value = ''" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
                <div class="clear"></div>
            </div>
        </div>
		<div class="clear"></div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</section>