<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php if ($this->getQuote()->hasVirtualItems()): ?>
    <h2 class="legend"><?php echo $this->__('Other Items in Your Order') ?></h2>
    <div class="grid_6 alpha col-narrow"></div>
    <div class="grid_6 omega col-wide">
        <h3><?php echo $this->__('Items') ?> <span class="separator">|</span> <a href="<?php echo $this->getVirtualProductEditUrl() ?>"><?php echo $this->__('Edit Items') ?></a></h3>
        <table class="data-table" id="unavailable-shipping-table">
            <col />
            <col width="1" />
            <thead>
                <tr>
                    <th><?php echo $this->__('Product Name') ?></th>
                    <th class="a-center"><?php echo $this->__('Qty') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($this->getVirtualQuoteItems() as $_item): ?>
                <tr>
                    <td><?php echo $this->getItemHtml($_item) ?></td>
                    <td class="a-center"><?php echo $_item->getQty() ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('unavailable-shipping-table')</script>
    </div>
    <div class="clear"></div>
<?php endif; ?>
