<?php 
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if($_menu): ?>
<div class="block block-navigation">
    <div class="block-title"><strong><span><?php echo $this->__('Store Catalog') ?></span></strong></div>
    <div class="block-content">
        <ul id="nav-sidebox">
        <?php echo $_menu ?>
        </ul>
    </div>
</div>
<script type="text/javascript">
document.observe("dom:loaded", function() {
    mainNav("nav-sidebox", {"show_delay":"100","hide_delay":"100"});
});
</script>
<?php endif ?>
