<?php
    $_productCollection = $this->getMyCollection();
    $category = $this->catName();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $this->productsAmount();
    
    $fancybox = MAGE::helper('ThemeOptionsLookbook')->getThemeOptionsLookbook('fancybox' );
?>
<?php // List Mode ?>
<ol class="products-list meigee-widget" id="products-list">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
		<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <li class="item<?php $_iterator=0; if($i == 0){echo ' first';} if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <div class="grid_3 alpha">
                <div class="product-img-box">
					<?php 
						/* Label New */ 
						if(MAGE::helper('ThemeOptionsLookbook')->getProductLabels($_product)){
							$keywords = array('label-new');
							$labelstring = MAGE::helper('ThemeOptionsLookbook')->getProductLabels($_product);
							$isKeyAvaliable = false;
							foreach($keywords as $word){
								if(strpos($labelstring, $word)){
									$isKeyAvaliable = true;
								}
							}
							if($isKeyAvaliable == false){
								echo '<div class="no-label-new">';
							}
							echo MAGE::helper('ThemeOptionsLookbook')->getProductLabels($_product);
							if($isKeyAvaliable == false){
								echo '</div> ';
							}
						}
					?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><div class="hover-box"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(300, null); ?>" <?php echo MAGE::helper('ThemeOptionsLookbook/Retina')->getRetinaData('list', $_product); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Hover Image */ echo MAGE::helper('ThemeOptionsLookbook')->getHoverImage($_product, 300, 600); ?></div></a>
                    <?php // Fancybox
                    if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
                        <a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
                    <?php endif; // End Fancybox ?>
					<div class="top-box">
						<?php if(Mage::getStoreConfig('ajax/general/enabledpro')){ ?>
						<button type="button" title="<?php echo $this->__('Quick View') ?>" class="button btn-quick-view" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><i class="circle-left"></i><i class="circle-right"></i><?php echo $this->__('Quick View') ?></span></span></button>
						<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
						<?php } ?>
					</div>
                </div>
            </div>
            <?php // Product description ?>
            <div class="grid_9 omega">
				<div class="product-shop">
					<?php if($_product->isSaleable()): ?>
						<p class="availability in-stock"><i class="icon-ok"></i><?php echo $this->__('In stock') ?></p>
					<?php else: ?>
						<p class="availability out-of-stock"><i class="icon-remove"></i><?php echo $this->__('Out of stock') ?></p>
					<?php endif; ?>
					<div class="left">
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
						<?php if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product) ?>
						<?php endif; ?>
					</div>
					<div class="clear"></div>
					<div class="item-box">
						<div class="grid_6 alpha">
							<div class="desc std">
								<h3><?php echo $this->__('Quick view:') ?></h3>
								<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
							</div>
						</div>
						<div class="grid_3 omega">
						<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
							<div class="price-button-box">
						<?php else: ?>
							<div class="no-button">
						<?php endif; ?>
								<?php
									$keywords = array('old-price', 'special-price', 'minimal-price-link', 'price-from', 'price-to', 'price-excluding-tax', 'price-including-tax');
									$exeptions = array('map-info');
									$exeption_flag = false;
									$pricestring = $this->getPriceHtml($_product, true);
									$isKeyAvaliable = false;
									foreach($keywords as $word){
										if(strpos($pricestring, $word)){
											$isKeyAvaliable = true;
										}
									}
									foreach($exeptions as $word){
										if(strpos($pricestring, $word)){
											$exeption_flag = true;
										}
									}
									if($exeption_flag == true){
										$isKeyAvaliable = false;
									}
								?>
								<div class="price-block<?php if($exeption_flag == true){echo ' click-for';} ?>">
									<?php if($isKeyAvaliable == false): ?>
									<label><?php echo $this->__('Price:') ?> </label>
									<?php endif; ?>
									<?php if($isKeyAvaliable == true): ?>
										<a class="price-details" href="#"><?php echo $this->__('Click for Price') ?></a>
										<div class="detailed-price-box">
									<?php endif; ?>
										<?php echo $this->getPriceHtml($_product, true) ?>
									<?php if($isKeyAvaliable == true): ?>
										</div>
									<?php endif; ?>
								</div>
								<?php if($_product->isSaleable()): ?>
									<?php if(Mage::getStoreConfig('ajax/general/enabledpro')){ ?>
										<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
											<span id='ajax_loader<?php echo $_product->getId()?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
											<?php else: ?>
												<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
												<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
										<?php endif; ?>
									<?php }else{ ?>
										 <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
									<?php } ?>
								<?php endif; ?>
							</div>
						</div>
						<div class="clear"></div>
					</div>
					<?php if(Mage::getStoreConfig('ajax/wishlistcompare/enabledpro')){ ?>
					 <ul class="add-to-links">
						<?php if ($this->helper('wishlist')->isAllow()) : ?>
							<li><a href="#" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId()?>");return false;' class="link-wishlist"><i class="icon-star"></i><?php echo $this->__('Add to Wishlist') ?><span id='ajax_wishlist_loading<?php echo $_product->getId()?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span></a></li>
						<?php endif; ?>
						<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
							<li><span class="separator">|</span> <a href="#" onclick='ajaxCompare("<?php echo $_compareUrl ?>","<?php echo $_product->getId()?>");return false;' class="link-compare"><i class="icon-exchange"></i><?php echo $this->__('Add to Compare') ?><span id='ajax_loading<?php echo $_product->getId()?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span></a></li>
						<?php endif; ?>
					</ul>
					<?php }else{ ?>
					<ul class="add-to-links">
					<?php if ($this->helper('wishlist')->isAllow()) : ?>
						<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><i class="icon-star"></i><?php echo $this->__('Add to Wishlist') ?></a></li>
					<?php endif; ?>
					<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
						<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="icon-exchange"></i><?php echo $this->__('Add to Compare') ?></a></li>
					<?php endif; ?>
					</ul>
					<?php } ?>
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('listing_likes')->toHtml() ?>
				</div>
            </div>
        </li>
    <?php if (++$i == $_collectionSize ) break; endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
	<script type="text/javascript">
		jQuery(document).ready(function(){
			jQuery('.ajax-fancybox').fancybox(
				{
				   hideOnContentClick : true,
				   width:600,
				   autoDimensions: true,
				   type : 'iframe',
				   showTitle: false,
				   scrolling: 'no',
				   onComplete: function(){
					jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
						jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
						jQuery.fancybox.resize();
					 });
				   }
				}
			);
			
		});
		function showOptions(id){
			jQuery('#fancybox'+id).trigger('click');
		}
		function setAjaxData(data,iframe){
			if(data.status == 'ERROR'){
				alert(data.message);
			}else{
				if(jQuery('.top-cart')){
					jQuery('.top-cart').replaceWith(data.sidebar);
				}
				/* if(jQuery('.header .links')){
					jQuery('.header .links').replaceWith(data.toplink);
				} */
				jQuery.fancybox.close();
			}
		}
		function setLocationAjax(url,id){
			url += 'isAjax/1';
			url = url.replace("checkout/cart","ajax/index");
			jQuery('#ajax_loader'+id).show();
			try {
				jQuery.ajax( {
					url : url,
					dataType : 'json',
					success : function(data) {
						jQuery('#ajax_loader'+id).hide();
						setAjaxData(data,false);
					}
				});
			} catch (e) {
			}
		}
	</script>