<?php
    $_productCollection = $this->getMyCollection();
	$gridMode = $this->sliderGridSelection();
	$visibleProducts = $this->getData('visible_products');
	$productCount = count($_productCollection);
	
	$category = $this->catName();
	$_helper = $this->helper('catalog/output');
	$_collectionSize = $this->productsAmount();

	$randId = $this->getWidgetId();
	
	$fancybox = MAGE::helper('ThemeOptionsLookbook')->getThemeOptionsLookbook('fancybox' );
?>
<?php // Slider ?>
<div class="slider-container widget-container">
	<?php if($productCount > $visibleProducts): ?>
		<div class="home-container <?php echo $gridMode.' alpha omega'; ?>">
			<div class="home-slider-conainer">
				<div class="home-slider es-carousel-wrapper" id="home-slider-<?php echo $randId; ?>">
					<div class="widget-slider">
						<ul class="products-grid carousel-ul">
							<?php $i=0; foreach ($_productCollection as $_product): ?>
							<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
							<li class="item">
								<div class="product-container">
									<div class="product-img-box">
										<?php  // Fancybox
										if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
												<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"><i class="icon-search"></i></a>
											<?php endif;
										// End Fancybox ?>
										<?php 
											/* Label New */ 
											if(MAGE::helper('ThemeOptionsLookbook')->getProductLabels($_product)){
												$keywords = array('label-new');
												$labelstring = MAGE::helper('ThemeOptionsLookbook')->getProductLabels($_product);
												$isKeyAvaliable = false;
												foreach($keywords as $word){
													if(strpos($labelstring, $word)){
														$isKeyAvaliable = true;
													}
												}
												if($isKeyAvaliable == false){
													echo '<div class="no-label-new">';
												}
												echo MAGE::helper('ThemeOptionsLookbook')->getProductLabels($_product);
												if($isKeyAvaliable == false){
													echo '</div> ';
												}
											}
										?>
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><div class="hover-box"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(300, null); ?>" <?php echo MAGE::helper('ThemeOptionsLookbook/Retina')->getRetinaData('grid', $_product); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Hover Image */ echo MAGE::helper('ThemeOptionsLookbook')->getHoverImage($_product, 300, 600); ?></div></a>
										<div class="top-box">
											<?php if(Mage::getStoreConfig('ajax/wishlistcompare/enabledpro')){ ?>
											 <ul class="add-to-links">
												<?php if ($this->helper('wishlist')->isAllow()) : ?>
													<li><a href="#" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId()?>");return false;' class="link-wishlist"><i class="icon-star"></i><?php echo $this->__('Add to Wishlist') ?><span id='ajax_wishlist_loading<?php echo $_product->getId()?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span></a></li>
												<?php endif; ?>
												<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
													<li><span class="separator">|</span> <a href="#" onclick='ajaxCompare("<?php echo $_compareUrl ?>","<?php echo $_product->getId()?>");return false;' class="link-compare"><i class="icon-exchange"></i><?php echo $this->__('Add to Compare') ?><span id='ajax_loading<?php echo $_product->getId()?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span></a></li>
												<?php endif; ?>
											</ul>
											<?php }else{ ?>
											<ul class="add-to-links">
											<?php if ($this->helper('wishlist')->isAllow()) : ?>
												<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><i class="icon-star"></i><?php echo $this->__('Add to Wishlist') ?></a></li>
											<?php endif; ?>
											<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
												<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="icon-exchange"></i><?php echo $this->__('Add to Compare') ?></a></li>
											<?php endif; ?>
											</ul>
											<?php } ?>
											<?php if(Mage::getStoreConfig('ajax/general/enabledpro')){ ?>
											<button type="button" title="<?php echo $this->__('Quick View') ?>" class="button btn-quick-view" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><i class="circle-left"></i><i class="circle-right"></i><?php echo $this->__('Quick View') ?></span></span></button>
											<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
											<?php } ?>
										</div>
									</div>
									<div class="actions">
										<div class="indent">
											<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
										</div>
									</div>
									<?php echo $this->getPriceHtml($_product, true); ?>
									<div class="clear"></div>
								</div>
							</li>
							<?php if (++$i > $_collectionSize-1 ) break; endforeach ?>
						</ul>
					</div>
					<div class = 'next'><i class="icon-angle-right"></i></div>
					<div class = 'prev unselectable'><i class="icon-angle-left"></i></div>
				</div>
			</div>
		</div>
		<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
		<script type="text/javascript">
		jQuery(window).load(function(){
			/* slides width corrector */
			if(!jQuery('body').hasClass('mobile-device')){
				function widthCorrector(){
					var widget = jQuery('#home-slider-<?php echo $randId; ?>');
					widget.children('style').remove();
					var widgetWidth = widget.width();
					widget.find('.widget-slider li.item:first').attr('style', '');
					var widgetItemWidth = widget.find('.widget-slider li.item:first').width();
					var columnsCount = Math.round(widgetWidth/widgetItemWidth);
					var columnWidth = Math.floor(widgetWidth/columnsCount);
					var widgetItemsCss = '<style type="text/css">#home-slider-<?php echo $randId; ?> .widget-slider li.item{width:'+ columnWidth +'px;}</style>';
					widget.append(widgetItemsCss);
				}
				widthCorrector();
				jQuery(window).resize(function(){widthCorrector()});
			}
		
			jQuery('#home-slider-<?php echo $randId; ?> .widget-slider').iosSlider({
			  responsiveSlideWidth: true,
			  snapToChildren: true,
			  desktopClickDrag: true,
			  infiniteSlider: false
			  <?php echo $this->getSliderOptions(); ?>,
			  /* navSlideSelector: '.sliderNavi .naviItem', */
			  navNextSelector: '#home-slider-<?php echo $randId; ?> .next',
			  navPrevSelector: '#home-slider-<?php echo $randId; ?> .prev'
			  <?php if(isset($sliderConfig ['autoSlide'])): ?>, autoSlide: <?php echo $sliderConfig ['autoSlide']; ?><?php endif; ?>
			  <?php if(isset($sliderConfig ['autoSlideTimer'])): ?>, autoSlideTimer: <?php echo $sliderConfig ['autoSlideTimer']; ?><?php endif; ?>
			});
			
			function widget_slider_height_<?php echo $randId; ?>(){
				setTimeout(function(){
					var widget_slider_height = 0;
					jQuery('.widget-container #home-slider-<?php echo $randId; ?> .products-grid li.item').each(function(){
						if(jQuery(this).height() > widget_slider_height){
							widget_slider_height = jQuery(this).height();
						}
					})
					jQuery('.widget-container #home-slider-<?php echo $randId; ?> .widget-slider').css({
						'min-height': (widget_slider_height+2),
						'height': 'auto'
					});
					
				}, 1000);
			}
			widget_slider_height_<?php echo $randId; ?>();
			jQuery(window).resize(function(){widget_slider_height_<?php echo $randId; ?>();});
		  });
		  
		  jQuery(document).ready(function(){
				jQuery('.widget-container').each(function(){
					if(!jQuery(this).prev().hasClass('page-title')){
						jQuery(this).addClass('no-title');
					}
				});
				
				jQuery('.ajax-fancybox').fancybox(
					{
					   hideOnContentClick : true,
					   width:600,
					   autoDimensions: true,
					   type : 'iframe',
					   showTitle: false,
					   scrolling: 'no',
					   afterLoad: function(){
							setTimeout(function(){
								var frameBodyHeight = jQuery('.fancybox-iframe').contents().find('body').height();
								if(jQuery(window).height() > frameBodyHeight+30){
									jQuery('.fancybox-inner').css('height', frameBodyHeight);
								}
							}, 1000);
						}
					}
				);
				
			});
			function showOptions(id){
				jQuery('#fancybox'+id).trigger('click');
			}
			function setAjaxData(data,iframe){
				if(data.status == 'ERROR'){
					alert(data.message);
				}else{
					if(jQuery('.top-cart')){
						jQuery('.top-cart').replaceWith(data.sidebar);
					}
					/* if(jQuery('.header .links')){
						jQuery('.header .links').replaceWith(data.toplink);
					} */
					jQuery.fancybox.close();
				}
			}
			function setLocationAjax(url,id){
				url += 'isAjax/1';
				url = url.replace("checkout/cart","ajax/index");
				jQuery('#ajax_loader'+id).show();
				try {
					jQuery.ajax( {
						url : url,
						dataType : 'json',
						success : function(data) {
							jQuery('#ajax_loader'+id).hide();
							setAjaxData(data,false);
						}
					});
				} catch (e) {
				}
			}
		</script>
	<?php else: ?>
		<div class="no-widget"><?php echo $this->__("Warning: Please make sure you have %s+ products to display in the slider, otherwise widget won't be displayed", $visibleProducts+1) ?></div>
	<?php endif; ?>
</div>
<?php 
	unset ($randId);
?>