<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        
		<?php if(!$_product->isGrouped()): ?>
		<div class="qty-block">
			<label for="qty"><?php echo $this->__('Qty:') ?></label>
			<div class="quantity-decrease" onclick="qtyDown()"><i class="icon-minus"></i></div>
			<input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
			<div class="quantity-increase" onclick="qtyUp()"><i class="icon-plus"></i></div>
			<div class="clear"></div>
		</div>
		<?php endif; ?>
		
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <span id='ajax_loader' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
        
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
	<script type="text/javascript">

		var qty_el = document.getElementById('qty'); 
		var qty = qty_el.value; 
		if(qty < 2){
			jQuery('.quantity_box_button_down').css({
			'visibility' : 'hidden'
			});
		}
		function qtyDown(){
			var qty_el = document.getElementById('qty'); 
			var qty = qty_el.value; 
			if( qty == 2) {
			jQuery('.quantity_box_button_down').css({
				'visibility' : 'hidden'
			});
			}
			if( !isNaN( qty ) && qty > 0 ){
			qty_el.value--;
			}         
			return false;
		}
		
		function qtyUp(){
			var qty_el = document.getElementById('qty'); 
			var qty = qty_el.value; 
			if( !isNaN( qty )) {
			qty_el.value++;
			}
			jQuery('.quantity_box_button_down').css({
			'visibility' : 'visible'
			});
			return false;
		}
    
    </script>
<?php endif; ?>