<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
/* @var $this Mage_Reports_Block_Product_Viewed */
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<section class="block-list block-viewed">
    <header>
        <h2><?php echo $this->__('Recently Viewed Products') ?></h2>
    </header>
    <div class="block-content">
        <ol id="recently-viewed-items">
        <?php foreach ($_products as $_item): ?>
            <li class="item">
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name') ?></a></p>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('recently-viewed-items');</script>
    </div>
</section>
<?php endif; ?>
