<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<div class="box">
    <div class="box-title">
        <h3><?php echo $this->__('Address Book') ?></h3>
        <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a>
    </div>
    <div class="box-content">
        <div class="grid_3 alpha">
            <h4><?php echo $this->__('Default Billing Address') ?></h4>
            <address>
                <?php echo $this->getPrimaryBillingAddressHtml() ?><br />
                <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
            </address>
        </div>
        <div class="grid_3 omega">
            <h4><?php echo $this->__('Default Shipping Address') ?></h4>
            <address>
                <?php echo $this->getPrimaryShippingAddressHtml() ?><br />
                <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
            </address>
        </div>
        <div class="clear"></div>
    </div>
</div>
<div class="clear"></div>
